{% set version = "1.5.0" %}

package:
  name: auditwheel
  version: {{ version }}

source:
  fn: auditwheel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/auditwheel/auditwheel-{{ version }}.tar.gz
  sha256: 7c8b2839e2ec119150014eea8c0e82598000650dd5212c29548b631633fa9ef8

build:
  number: 0
  skip: True  # [py2k or not linux]
  entry_points:
    - auditwheel = auditwheel.main:main

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - setuptools
    - pip
    - pyelftools
    - typing      # [py<35]

test:
  commands:
    - auditwheel -h

about:
  home: https://github.com/pypa/auditwheel
  license: MIT
  summary: Linux wheel verification tool to ensure compatibility

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
